services:
  postgres:
    image: postgis/postgis:16-3.4   # обычный postgres НЕ подойдёт: нет PostGIS
    container_name: heat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: heat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d heat"]  # было "-d path" — опечатка
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heat-trace-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/heat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
"""services:

  # PostgreSQL
  postgres:
    image: postgres:18
#    restart: unless-stopped
    environment:
      POSTGRES_DB: heat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d path"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#
#volumes:
#  postgres_data:"""