server:
  port: 8080
  tomcat:
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # схему создаёт Flyway, Hibernate только валидирует
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB

# Настройки springdoc / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# Actuator (health, info)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
